### ISSUE TITLE
🐛 Bug: "Hack" command and Clyde command not working

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#149]
on the run of command, receives an error.

```
(node:37813) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.execute (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/commands/Fun/hack.js:7:13)
    at module.exports (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/events/guild/message.js:16:34)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/Users/jasper/Desktop/Coding/Projects/ProjectHeptagram/Heptagram/node_modules/ws/lib/receiver.js:78:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37813) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37813) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by j-dogcoder** [comment]
**_NOTE: Changes only on staged branch._**

**Comment by squarecylinder** [comment]
.take

**Comment by squarecylinder** [comment]
PR #166 is up for this.
