### ISSUE TITLE
Bug with admin commands 

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#17]
My error message

(```
node:75058) UnhandledPromiseRejectionWarning: ReferenceError: ADMIN_ROLE_ID is not defined
    at Object.execute (/Users/jasper/Desktop/Coding/Heptagram/commands/Moderation/clear.js:9:44)
    at Client.<anonymous> (/Users/jasper/Desktop/Coding/Heptagram/main.js:40:32)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/Users/jasper/Desktop/Coding/Heptagram/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:75058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:75058) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by j-dogcoder** [comment]
Hold, I may be on the wrong branch

**Comment by j-dogcoder** [comment]
Nope. Still broken

**Comment by j-dogcoder** [comment]
@thinkverse?

**Comment by thinkverse** [comment]
Did you pull down the latest changes? `ROLE_ADMIN_ID` is not referenced anywhere in the clear command, you must have an old version locally. Look at the code here on GitHub the reference is not there. 🤷‍♂️

**Comment by j-dogcoder** [comment]
Huh. Let me see...

**Comment by j-dogcoder** [comment]
Now it's throwing something else entirely. 

`(node:76506) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'admin' of undefined
    at Object.execute (/Users/jasper/Desktop/Coding/Heptagram/commands/Moderation/clear.js:9:50)
    at Client.<anonymous> (/Users/jasper/Desktop/Coding/Heptagram/main.js:39:32)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/Users/jasper/Desktop/Coding/Heptagram/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:76506) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:76506) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by j-dogcoder** [comment]
I sent you the discord server invite even though the server is not done. This way you can test the bot when it's online.

**Comment by j-dogcoder** [comment]
All good now.
