### ISSUE TITLE
🐛 BUG:  Command fails when not in wrapped in execute.

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#97]
In this particular example, this is the lock.js file. I would love to have the handler fixed entirely though.

**Comment by j-dogcoder** [comment]
### **Error Message:**

```
TypeError: client.commands.get(...).execute is not a function
    at module.exports (/Users/jasper/Desktop/Coding/Heptagram/events/client/message.js:12:34)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/Users/jasper/Desktop/Coding/Heptagram/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/Users/jasper/Desktop/Coding/Heptagram/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/Users/jasper/Desktop/Coding/Heptagram/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/Users/jasper/Desktop/Coding/Heptagram/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/Users/jasper/Desktop/Coding/Heptagram/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/Users/jasper/Desktop/Coding/Heptagram/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
```

**Comment by j-dogcoder** [comment]
<img width="874" alt="Screen Shot 2021-04-21 at 7 40 01 AM" src="https://user-images.githubusercontent.com/65788728/115547946-e1046600-a274-11eb-8201-8fb6177c7d58.png">
